import { useAppContext } from '@/context/appContext'
import { useContato } from '@/hooks'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useEffect } from 'react'

const contato = () => {
  const router = useRouter()

  const { contato, handleContatoInputChange, setContato, valido } = useAppContext()
  const { validarContato, criarContato } = useContato()

  useEffect(() => {
    setContato({ id: 0, nome: '', email: '', mensagem: '' })
  }, [])

  useEffect(() => {
    validarContato()
  }, [contato])

  const { nome, email, mensagem } = contato

  return (
    <>
      <Head>
        <title>Daviagens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container d-flex align-items-center flex-column'>
        <div className="text-center mt-5 ">
          <h1>Entrar em contato</h1>
          <p style={{ maxWidth: 550 }}>
            Estamos aqui para ouvir você! Entre em contato conosco e deixe sua mensagem. Sua opinião é fundamental para o
            nosso
            crescimento e aprimoramento.
          </p>
        </div>

        <section className="my-5 flex-grow-1" id="formulario">
          <form className="d-flex gap-5 flex-column">
            <div className="mb-3">
              <label htmlFor="nome" className="form-label text-white">Nome</label>
              <input type="text" className="form-control" id="nome" name="nome" onChange={handleContatoInputChange} value={nome} required />
            </div>
            <div className="mb-3">
              <label htmlFor="email" className="form-label text-white">Email</label>
              <input type="email" className="form-control" id="email" name="email" onChange={handleContatoInputChange} value={email} required />
            </div>
            <div className="mb-3">
              <label htmlFor="mensagem" className="form-label text-white" >Mensagem</label>
              <textarea
                className="form-control"
                id="mensagem"
                name='mensagem'
                style={{ resize: 'none' }}
                rows={5}
                onChange={handleContatoInputChange}
                value={mensagem}
                required></textarea>
            </div>
            <a
              type="submit"
              className={`btn btn-primary me-auto ${valido == false ? 'disabled' : ''}`}
              onClick={() => {
                criarContato()
                router.reload()
              }}
            >Enviar</a>
          </form>
        </section>
      </main>
    </>
  )
}

export default contato