import React, { useEffect } from 'react'
import Head from 'next/head'
import { DestinationCard } from '@/components'
import { useDestinos } from '@/hooks'
import { useAppContext } from '@/context/appContext'

const destinos = () => {
  const { listarDestinos, filtrarNacionais, filtrarInternacionais, mostrarTodos } = useDestinos()
  const { destinos } = useAppContext()

  useEffect(() => {
    listarDestinos()
  }, [])

  console.log(destinos)
  return (
    <>
      <Head>
        <title>Daviagens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container d-flex flex-column align-content-center '>
        <div className="text-center mt-3 ">
          <h1>Destinos</h1>
          <p className='mx-auto ' style={{ maxWidth: 550 }}>
            Explore nosso catálogo de destinos e embarque em uma jornada única pelo fascinante mosaico de maravilhas que o
            mundo tem a oferecer.
          </p>
        </div>
        <section className="my-5 ">
          <h2 className="text-center mb-3">Nacionais</h2>
          <div className="d-flex gap-5 flex-wrap justify-content-around mx-auto " id="nacionais">
            {destinos.map((destino, i) => (
              destino.tipo === "NACIONAL" &&
              <DestinationCard
                key={i}
                destino={destino}
              />
            ))}
          </div>
        </section>

        <section className="my-5 ">
          <h2 className="text-center mb-3">Internacionais</h2>
          <div className="d-flex gap-5 flex-wrap justify-content-around mx-auto " id="nacionais">
            {destinos.map((destino, i) => (
              destino.tipo === "INTERNACIONAL" &&
              <DestinationCard
                key={i}
                destino={destino}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  )
}

export default destinos