import Head from 'next/head'
import { Carousel, DestinationCard, PromotionCard } from '@/components'
import { listaDestinos } from '@/constants/data'

export default function Home() {
  return (
    <>
      <Head>
        <title>Daviagens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>


        <section className="container my-5 d-flex gap-5 " id="destinos">

          <div className="destinos-description d-flex flex-column justify-content-evenly align-items-start">
            <h2>Destinos</h2>
            <p>
              Explore os destinos mais deslumbrantes do mundo com a nossa agência de viagens. De paisagens exuberantes a
              culturas
              fascinantes, viva experiências únicas que ficarão gravadas em sua alma para sempre!
            </p>
            <a className="btn btn-primary" href="../destinos/destinos.html">Ver mais destinos</a>
          </div>

          <div className="card-section d-flex gap-3">
            <DestinationCard destino={listaDestinos[2]} />
            <DestinationCard destino={listaDestinos[5]} />
          </div>

        </section>

        <section className="container d-flex flex-row-reverse gap-5" id="promocoes">

          <div className="promocoes-description d-flex flex-column justify-content-evenly align-items-end ">
            <h2>Promoções</h2>
            <p>
              Descubra o mundo com nossas imperdíveis promoções de viagens! Aventure-se em destinos fascinantes e crie
              memórias
              inesquecíveis, enquanto aproveita descontos exclusivos para viver experiências únicas pelo globo.
            </p>
            <a className="btn btn-primary" href="../promocoes/promocoes.html">Ver mais promoções</a>
          </div>

          <div className="card-section d-flex gap-3">
            <PromotionCard destino={listaDestinos[7]} />
            <PromotionCard destino={listaDestinos[0]} />
          </div>
        </section>


      </main>
    </>
  )
}
