import Head from 'next/head'
import { Carousel, DestinationCard, PromotionCard } from '@/components'
import { listaDestinos } from '@/constants/data'
import { useEffect, useState } from 'react'
import { useDestinos } from '@/hooks'

export default function Home() {
  const { destinos, listarDestinos } = useDestinos()

  const [carouselDestinos, setCarouselDestinos] = useState([])
  const [teste, setTeste] = useState([])
  const [promocoes, setPromocoes] = useState([])

  console.log(destinos)

  useEffect(() => {
    let numeros = []
    while (numeros.length < 7) {
      let num = Math.floor(Math.random() * 11)
      if (numeros.indexOf(num) === -1) numeros.push(num)
    }
    setCarouselDestinos(numeros.slice(0, 3))
    setTeste(numeros.slice(3, 5))
    setPromocoes(numeros.slice(5, 7))

    listarDestinos()
  }, [])

  return (
    <>
      <Head>
        <title>Daviagens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Carousel carouselDestinos={carouselDestinos} />


        <section className="container my-5 d-flex gap-5 " id="destinos">

          <div className="destinos-description d-flex flex-column justify-content-evenly align-items-start">
            <h2>Destinos</h2>
            <p>
              Explore os destinos mais deslumbrantes do mundo com a nossa agência de viagens. De paisagens exuberantes a
              culturas
              fascinantes, viva experiências únicas que ficarão gravadas em sua alma para sempre!
            </p>
            <a className="btn btn-primary" href="/destinos">Ver mais destinos</a>
          </div>

          <div className="card-section d-flex gap-3">

            {/* {destinos.map((destino, i) => (
              <DestinationCard
                key={i}
                destino={destinos[1]} />
            ))} */}
          </div>

        </section>

        <section className="container d-flex flex-row-reverse gap-5" id="promocoes">

          <div className="promocoes-description d-flex flex-column justify-content-evenly align-items-end ">
            <h2>Promoções</h2>
            <p>
              Descubra o mundo com nossas imperdíveis promoções de viagens! Aventure-se em destinos fascinantes e crie
              memórias
              inesquecíveis, enquanto aproveita descontos exclusivos para viver experiências únicas pelo globo.
            </p>
            <a className="btn btn-primary" href="/promocoes">Ver mais promoções</a>
          </div>

          <div className="card-section d-flex gap-3">
            {/*  {promocoes.map((destino, i) => (
              <PromotionCard
                key={i}
                destino={listaDestinos[destino]} />
            ))} */}
          </div>
        </section>


      </main>
    </>
  )
}
