import React, { useEffect } from 'react'
import Head from 'next/head'
import { PromotionCard } from '@/components'
import { useDestinos, usePromotions } from '@/hooks'
import { useAppContext } from '@/context/appContext'

const promocoes = () => {
  // const { listarMenorPreco, listarMaiorDesconto, listarMaiorPreco, listarMenorDesconto } = usePromotions()
  const { listarDestinos } = useDestinos()
  const { destinos } = useAppContext()

  useEffect(() => {
    listarDestinos()
  }, [])
  return (
    <>
      <Head>
        <title>Daviagens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container d-flex flex-column align-content-center '>
        <div className="text-center mt-3 ">
          <h1>Promoções</h1>
          <p style={{ maxWidth: 550 }} className='mx-auto'>
            Desbrave o mundo com ofertas imperdíveis! Descubra destinos extraordinários com descontos exclusivos em nossos
            pacotes de viagem. Sua próxima aventura começa aqui!
          </p>
        </div>
        <section className="my-5 ">
          <div className="d-flex gap-5 flex-wrap justify-content-around" id="descontos">
            {destinos.map((destino, i) => (
              <PromotionCard
                key={i}
                destino={destino}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  )
}

export default promocoes